# Generated by Django 4.1 on 2022-08-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="respondent",
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ConditionalOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "negative_response_question_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negative_response_question_order",
                        to="survey_app.questionorder",
                    ),
                ),
                (
                    "positive_response_question_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positive_response_question_order",
                        to="survey_app.questionorder",
                    ),
                ),
                (
                    "question_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_order",
                        to="survey_app.questionorder",
                    ),
                ),
                (
                    "response_question_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_question_order",
                        to="survey_app.questionorder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
